#!/usr/bin/env bash
#
# Force the Android target SDK in the generated Bubblewrap project.
#
# This exists because `twa-manifest.json` has no `targetSdkVersion` field —
# checked against the TwaManifestJson interface in @bubblewrap/core, which
# carries `minSdkVersion` and no target counterpart. The target level comes
# from Bubblewrap's own project template instead, so the only place to set it
# is the generated `android/app/build.gradle`.
#
# That file is regenerated by `bubblewrap update`, which means this has to run
# AFTER the update and BEFORE the build, every time. It is not a one-off edit.
#
# Why it matters: Google Play requires new apps and app updates to target
# Android 16 (API 36) from 31 August 2026. Bubblewrap's template has lagged the
# current level before, so shipping whatever the template happens to emit is
# how a release gets rejected.
#
# Deliberately fails when it cannot find the setting rather than passing
# quietly. A silent no-op here produces an AAB that builds, installs, runs, and
# is refused at upload — the failure would surface at the worst moment.
#
# Usage:
#   scripts/android/target-sdk.sh          # set target + compile SDK to 36
#   TARGET_SDK=37 scripts/android/target-sdk.sh

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TARGET_SDK="${TARGET_SDK:-36}"
GRADLE="$ROOT/android/app/build.gradle"

[[ -f "$GRADLE" ]] || {
   echo "no $GRADLE — run 'bubblewrap init' or 'bubblewrap update' first" >&2
   exit 1
}

# Both spellings: AGP renamed `targetSdkVersion`/`compileSdkVersion` to
# `targetSdk`/`compileSdk`, and which one the template emits depends on the
# Bubblewrap version. Whichever is present gets rewritten.
#
# compileSdk moves too: it must be >= targetSdk or Gradle refuses to configure.
patched=0
for key in targetSdkVersion compileSdkVersion targetSdk compileSdk; do
   if grep -qE "^[[:space:]]*${key}[[:space:]]+[0-9]+" "$GRADLE"; then
      # Not `sed -i -E`: BSD sed (macOS) requires an argument to -i and would
      # swallow -E as the backup suffix, dropping extended regex and breaking
      # the \1 backreference. A temp file behaves the same on both seds.
      sed -E "s/^([[:space:]]*)${key}[[:space:]]+[0-9]+/\1${key} ${TARGET_SDK}/" "$GRADLE" > "$GRADLE.tmp"
      mv "$GRADLE.tmp" "$GRADLE"
      patched=$((patched + 1))
   fi
done

if [[ "$patched" -eq 0 ]]; then
   echo "could not find a target/compile SDK setting in $GRADLE" >&2
   echo "Bubblewrap's template has probably changed shape — inspect it and fix this script." >&2
   exit 1
fi

echo "target/compile SDK set to ${TARGET_SDK} (${patched} setting(s) rewritten)"
grep -nE "^[[:space:]]*(target|compile)Sdk(Version)?[[:space:]]+[0-9]+" "$GRADLE"
