#!/usr/bin/env bash
#
# SEO verification smoke test for Metrics Adda (Nuxt SEO suite).
#
# Boots the production build locally and asserts every SEO surface renders:
# robots.txt, sitemap + hreflang, meta/OG/Twitter tags, canonical, in-head
# hreflang, JSON-LD, and the dynamic OG image.
#
# Usage:
#   scripts/seo/verify.sh                 # build if needed, boot server, check
#   BUILD=1 scripts/seo/verify.sh         # force a fresh build first
#   PORT=4000 scripts/seo/verify.sh       # use a different local port
#   BASE_URL=https://foo.vercel.app scripts/seo/verify.sh
#                                         # check a remote URL (no build/boot)
#
# Exit code = number of failed checks (0 = all green).

set -uo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

PORT="${PORT:-3123}"
# Routes checked for the full meta/canonical/OG/JSON-LD set. Add a page
# here when you add one to app/pages, so its metadata is asserted too.
ROUTES="${ROUTES:-/ /weight-converter /height-converter /temperature-converter /word-counter /password-generator}"
SERVER_PID=""

# ── pretty output ────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
   G=$'\e[32m'; R=$'\e[31m'; Y=$'\e[33m'; C=$'\e[36m'; D=$'\e[2m'; B=$'\e[1m'; X=$'\e[0m'
else
   G=""; R=""; Y=""; C=""; D=""; B=""; X=""
fi
PASS=0; FAIL=0

pass()    { printf "  ${G}✔${X} %s\n" "$1"; PASS=$((PASS + 1)); }
fail()    { printf "  ${R}✗${X} %s${D} — %s${X}\n" "$1" "$2"; FAIL=$((FAIL + 1)); }
section() { printf "\n${B}%s${X}\n" "$1"; }

# assert_contains "<desc>" "<content>" "<regex>"
assert_contains() {
   if grep -qiE -- "$3" <<<"$2"; then pass "$1"; else fail "$1" "missing: $3"; fi
}

# ── server lifecycle ─────────────────────────────────────────────────────────
cleanup() {
   [[ -n "$SERVER_PID" ]] && kill "$SERVER_PID" 2>/dev/null
}
trap cleanup EXIT INT TERM

if [[ -n "${BASE_URL:-}" ]]; then
   BASE="${BASE_URL%/}"
   section "Target: ${C}${BASE}${X} ${D}(remote — no build/boot)${X}"
else
   BASE="http://localhost:${PORT}"
   if [[ "${BUILD:-0}" == "1" || ! -f .output/server/index.mjs ]]; then
      printf "${D}Building production output…${X}\n"
      if ! bun run build >/tmp/seo-build.log 2>&1; then
         printf "${R}Build failed.${X} See /tmp/seo-build.log\n"; tail -20 /tmp/seo-build.log; exit 1
      fi
   fi
   printf "${D}Starting server on :%s …${X}\n" "$PORT"
   PORT="$PORT" bun run .output/server/index.mjs >/tmp/seo-server.log 2>&1 &
   SERVER_PID=$!
   ready=0
   for _ in $(seq 1 30); do
      if curl -sf -o /dev/null "$BASE/"; then ready=1; break; fi
      sleep 1
   done
   if [[ "$ready" != "1" ]]; then
      printf "${R}Server never became ready.${X} See /tmp/seo-server.log\n"; tail -20 /tmp/seo-server.log; exit 1
   fi
   section "Target: ${C}${BASE}${X}"
fi

# ── fetch once, reuse ────────────────────────────────────────────────────────
ROBOTS="$(curl -s "$BASE/robots.txt")"
# Single-locale site, so @nuxtjs/sitemap serves one flat sitemap here rather
# than an index fanning out to per-language files.
SITEMAP="$(curl -s "$BASE/sitemap.xml")"

# ── robots ───────────────────────────────────────────────────────────────────
section "robots.txt"
assert_contains "generated by nuxt-robots" "$ROBOTS" "nuxt-robots"
assert_contains "references the sitemap"   "$ROBOTS" "Sitemap: https?://"
assert_contains "site is indexable"        "$ROBOTS" "User-agent: \*"

# ── sitemap ──────────────────────────────────────────────────────────────────
section "sitemap"
assert_contains "sitemap served"     "$SITEMAP" "<urlset"
assert_contains "sitemap has entries" "$SITEMAP" "<loc>https?://"

# ── per-route checks ─────────────────────────────────────────────────────────
for route in $ROUTES; do
   section "route ${C}${route}${X}"
   HTML="$(curl -s "$BASE$route")"

   assert_contains "has <title>"          "$HTML" "<title>[^<]+</title>"
   assert_contains "meta description"     "$HTML" "name=\"description\" content=\"[^\"]+\""
   assert_contains "canonical URL"        "$HTML" "rel=\"canonical\""
   assert_contains "og:title"             "$HTML" "property=\"og:title\""
   assert_contains "og:image"             "$HTML" "property=\"og:image\""
   assert_contains "twitter summary card" "$HTML" "name=\"twitter:card\" content=\"summary_large_image\""
   # No hreflang assertions: the site is single-locale, and hreflang annotates
   # alternates. Emitting it with nothing to point at would be the bug.
   assert_contains "declares lang"        "$HTML" "<html[^>]*lang=\"en\""
   assert_contains "schema.org JSON-LD"   "$HTML" "application/ld\+json"
   assert_contains "listed in sitemap"    "$SITEMAP" "<loc>[^<]*${route%/}/?</loc>"

   # The OG card must actually render, not just be linked.
   OG_PATH="$(grep -oiE 'property="og:image" content="[^"]*"' <<<"$HTML" \
      | sed -E 's/.*content="([^"]*)".*/\1/' | sed -E 's#^https?://[^/]+##' | head -1)"
   if [[ -z "$OG_PATH" ]]; then
      fail "og:image URL found" "no og:image meta tag"
   else
      read -r OG_CODE OG_TYPE OG_SIZE < <(curl -s -o /dev/null -w "%{http_code} %{content_type} %{size_download}" "$BASE$OG_PATH")
      if [[ "$OG_CODE" == "200" && "$OG_TYPE" == image/png* && "${OG_SIZE:-0}" -gt 1000 ]]; then
         pass "OG card renders PNG (${OG_SIZE} bytes)"
      else
         fail "OG card renders PNG" "code=$OG_CODE type=$OG_TYPE size=${OG_SIZE:-0}"
      fi
   fi
done

# ── summary ──────────────────────────────────────────────────────────────────
printf "\n${B}Summary${X}  ${G}%d passed${X}  ${R}%d failed${X}\n" "$PASS" "$FAIL"
exit "$FAIL"
